<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_TestDevice" Id="{88d37211-e048-4fcc-a4d0-a3e1706c8869}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestDevice IMPLEMENTS I_Focus, I_Nasmyth
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_TestDevice">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>