name: Checkout Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Windows, X64, TwinCAT]

    steps:
      - uses: actions/checkout@v4

      - name: Show workspace
        shell: powershell
        run: |
          Write-Host "Workspace: $env:GITHUB_WORKSPACE"
          Get-ChildItem -Recurse $env:GITHUB_WORKSPACE
